# Generated by Django 4.2.16 on 2026-03-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_crimes', models.IntegerField()),
                ('rape', models.IntegerField(default=0)),
                ('molestation', models.IntegerField(default=0)),
                ('kidnapping', models.IntegerField(default=0)),
                ('cruelty_by_husband', models.IntegerField(default=0)),
                ('dowry_deaths', models.IntegerField(default=0)),
                ('harassment', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='DistrictData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('total_crimes', models.IntegerField()),
                ('rape', models.IntegerField(default=0)),
                ('molestation', models.IntegerField(default=0)),
                ('kidnapping', models.IntegerField(default=0)),
                ('cruelty_by_husband', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['year', 'district'],
            },
        ),
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('date_published', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
