# Generated by Django 4.2.16 on 2026-03-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_districtdata_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtdata',
            name='dowry_deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='districtdata',
            name='harassment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='districtdata',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='districtdata',
            name='other',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='districtdata',
            name='cruelty_by_husband',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='districtdata',
            name='kidnapping',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='districtdata',
            name='molestation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='districtdata',
            name='rape',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='districtdata',
            name='total_crimes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
