# Generated by Django 4.2.16 on 2026-04-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_districtdata_dowry_deaths_districtdata_harassment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
