# Generated by Django 4.2.16 on 2026-04-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsupdate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
