# Generated by Django 4.2.16 on 2026-03-19 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(choices=[('domestic_violence', 'Domestic Violence / DV Act'), ('sexual_offences', 'Sexual Offences / POCSO'), ('family_law', 'Family Law'), ('criminal_law', 'Criminal Law'), ('human_rights', 'Human Rights'), ('labour_law', 'Labour / Workplace Harassment'), ('general', 'General Practice'), ('other', 'Other')], max_length=50)),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], max_length=100)),
                ('languages', models.CharField(help_text='e.g. Malayalam, English, Hindi', max_length=200)),
                ('experience_years', models.IntegerField(default=0, help_text='Years of experience')),
                ('bar_council_no', models.CharField(blank=True, help_text='Bar Council registration number', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('pro_bono', models.BooleanField(default=False, help_text='Available for free pro-bono work')),
                ('reduced_cost', models.BooleanField(default=False, help_text='Available for reduced-cost work')),
                ('availability', models.CharField(blank=True, help_text='e.g. Weekends, evenings, full-time', max_length=300)),
                ('bio', models.TextField(blank=True, help_text='Brief description of your experience and how you can help')),
                ('is_approved', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survivor_name', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='volunteers.lawyervolunteer')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
