# Generated by Django 4.2.16 on 2026-03-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('purpose', models.CharField(choices=[('partnership', 'Partnership / Collaboration'), ('academic', 'Academic Research'), ('media', 'Media Inquiry'), ('ngo', 'NGO / Civil Society'), ('feedback', 'Feedback'), ('general', 'General Inquiry')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
