# Generated by Django 4.2.16 on 2026-03-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(choices=[('domestic_violence', 'Domestic Violence / Cruelty by Husband'), ('rape', 'Rape / Sexual Assault'), ('molestation', 'Molestation / Sexual Harassment'), ('stalking', 'Stalking / Cyberstalking'), ('kidnapping', 'Kidnapping'), ('dowry', 'Dowry Harassment / Dowry Death'), ('trafficking', 'Human Trafficking'), ('workplace', 'Workplace Harassment'), ('other', 'Other')], max_length=50)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('referred', 'Referred'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
