# Generated by Django 4.2.16 on 2026-03-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='incident_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='institution',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='needs_legal_help',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='reported_to_police',
            field=models.BooleanField(default=False),
        ),
    ]
