# Generated by Django 4.2.16 on 2026-03-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportrequest_evidence_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='help_court_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='help_filing_complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='help_legal_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='help_ngo_referral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='help_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='help_other_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='help_recovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='help_safety_planning',
            field=models.BooleanField(default=False),
        ),
    ]
