# Generated by Django 4.2.16 on 2026-03-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('new_law', 'New Law'), ('court_ruling', 'Court Ruling'), ('policy_gap', 'Policy Gap'), ('recommendation', 'Recommendation'), ('law_update', 'Law Update')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('source', models.CharField(blank=True, help_text='Source URL or reference', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
